apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-master-config
data:
  redis.conf: |
    # Redis configuration file
    port 6379
    bind 0.0.0.0
    protected-mode no
    # Enable persistence
    appendonly yes
    # Set a password for authentication (replace with a secure password)
    requirepass your_redis_master_password
